---
output: html_document
editor_options: 
  chunk_output_type: console
---
\newpage
\tableofcontents 
\newpage
\listoftables 
\newpage
\listoffigures 
\newpage

```{r setup, include=FALSE}
# Set your working directory
# Load packages
getwd()
library(tidyverse)
library(sf)
library(ggplot2)
library(dplyr)
library(mapview)
library(leaflet)
library("GGally")
library(readxl)
# Set theme
mytheme <- theme_classic(base_size = 14) +
  theme(axis.text = element_text(color = "black"), 
        legend.position = "top")
theme_set(mytheme)

```

```{r} 
# Read the dataframes
census_processed<- read.csv("Data/census_processed(2020-2024).csv", stringsAsFactors = T)
census_processed<- read.csv("Data/census_processed(2020-2024).csv",stringsAsFactors = T)
census_processed <- census_processed %>% 
  mutate(MEAN = rowMeans(across(X2020:X2024)))
substring(census_processed$State, 2, nchar(census_processed))
colnames(census_processed) <- c("State","2020","2021","2022","2023","2024")

Energy_investment<- read.csv("Data/Energy_investment_by_county.csv", stringsAsFactors = T)

disasters <- read.csv("./Data/DisasterDeclarationsSummaries.csv", stringsAsFactors = T)


#Disaster dataset: https://www.fema.gov/openfema-data-page/disaster-declarations-summaries-v2

states <- st_read("./Data/Spatial/cb_2018_us_state_20m.shp", stringsAsFactors = T)

census_2021 <- read.csv("ACSSPP1Y2021.S0201-2025-11-29T154845.csv", stringsAsFactors = T)

census_2022 <- read.csv("ACSSPP1Y2022.S0201-2025-11-29T154817.csv", stringsAsFactors = T)

census_2023 <- read.csv("ACSSPP1Y2023.S0201-2025-11-29T154759.csv", stringsAsFactors = T)

census_2024 <- read.csv("ACSSPP1Y2024.S0201-2025-11-29T154742.csv", stringsAsFactors = T)
```

```{r}
#census_2021.columns = census_2021.columns.str.replace(' ','')
census2021 <- as.data.frame(t(census_2021))
colnames(census2021) <-c(census2021[1,])

census2021clean <- census2021[-1,]
#census2021clean <- census2021[-c(seq(2,length(census2021),2)),]

colnames(census2021clean) <- str_trim(colnames(census2021clean))



rownames(census2021clean) <- str_sub(rownames(census2021clean), end =-29)
#rownames(census2021clean) <- gsub("."," ", rownames(census2021clean))

census2021clean <- census2021clean %>% 
  select("Total population", "Male", "Female", "Under 5 years", "5 to 17 years", "Median age (years)", "Median household income (dollars)", "Occupied housing units","Gas", "Electricity","All other fuels","No fuel used") %>% 
  mutate(year = 2021, State = rownames(census2021clean))
  #mutate(State = sub("."," ", State)) # Remove the dots in State names
census2021clean$State <- gsub( "\\."," ",census2021clean$State)

census2021clean$`Total population` <- as.numeric(str_trim(census2021clean$`Total population`))
census2021clean$`Male` <- as.numeric(str_trim(census2021clean$`Male`))
census2021clean$Female <- as.numeric(str_trim(census2021clean$`Female`))
census2021clean$`Under 5 years` <- as.numeric(str_trim(census2021clean$`Under 5 years`))
census2021clean$`5 to 17 years` <- as.numeric(str_trim(census2021clean$`5 to 17 years`))
census2021clean$`Median age (years)` <- as.numeric(str_trim(census2021clean$`Median age (years)`))
census2021clean$`Median household income (dollars)` <- as.numeric(str_trim(census2021clean$`Median household income (dollars)`))
census2021clean$`Occupied housing units` <- as.numeric(str_trim(census2021clean$`Occupied housing units`))
census2021clean$Gas <- as.numeric(str_trim(census2021clean$Gas))
census2021clean$Electricity <- as.numeric(str_trim(census2021clean$Electricity))
census2021clean$`All other fuels` <- as.numeric(str_trim(census2021clean$`All other fuels`))
census2021clean$`No fuel used` <- as.numeric(str_trim(census2021clean$`No fuel used`))

 
census2021clean <- census2021clean%>%
  mutate(child=`Under 5 years` + `5 to 17 years`)


## Energy dataset
Energy_investment2021 <- Energy_investment %>% 
  select(c("STATEFP":"GEOID_fips"),"stname", "TotalFedAction_EnergyEnv_2021")


Energy_investment2021$TotalFedAction_EnergyEnv_2021 <- 
  gsub("\\$ ", "", Energy_investment2021$TotalFedAction_EnergyEnv_2021)

Energy_investment2021 <- Energy_investment2021 %>%
  mutate(TotalFedAction_EnergyEnv_2021 =
           as.numeric(
             gsub(",", "", trimws(TotalFedAction_EnergyEnv_2021)))
         ) %>% 
  na.omit(TotalFedAction_EnergyEnv_2021) %>% 
  filter(!stname == "")
  
summary(Energy_investment2021)

Energy_investment2021_group <- Energy_investment2021 %>% 
  group_by(STATEFP, stname) %>% 
  summarise(Total_EE_Investment = sum(TotalFedAction_EnergyEnv_2021)) %>% 
  mutate(Year = 2021)

#Disaster
states_names <- data.frame(abbrev = states$STUSPS,
                           state = states$NAME)
disaster2021 <- disasters %>% 
  select(c(state:incidentType), fipsStateCode,fipsCountyCode) %>% 
  filter(fyDeclared %in% c(2021)) %>% 
  arrange(state) %>% 
  group_by(state) %>% 
  summarise(Disasters = n())
disaster2021 <- left_join(disaster2021, states_names, by = c("state" = "abbrev"))

#Political opinions
Regulate <- read_excel("Data/Regulate_percentage(2021~2024).xlsx")
colnames(Regulate) 

combined2021 <- left_join(census2021clean, Energy_investment2021_group, by = c("State" = "stname"))

combined2021 <- left_join(combined2021, disaster2021, by = c("State" = "state.y"))

combined2021 <- left_join(combined2021, Regulate, by = c("State" = "GeoName"))

#spatial2021 <- st_as_sf(combined2021)
#mapview(spatial2021, z = "Male")
```

# Rationale and Research Questions



\newpage

# Dataset Information
```{r}

summary(census2021clean)
summary(Energy_investment2021_group)
```



\newpage

# Exploratory Analysis 

```{r}
cols <- c(1,3,6,7,9,10,15,17,20,24)
ggpairs(combined2021, columns = cols, title = "",  
        axisLabels = "show",
        lower = list(continuous = wrap("points", size = 0.4)),
        upper = list(continuous = wrap("cor", size = 3)))+
  theme( #adjust the axis labels
    axis.text.x = element_text(size = 5),
    axis.text.y = element_text(size = 5),
    strip.text.x = element_text(size = 5),  
    strip.text.y = element_text(size = 5)
  )
```


\newpage

# Analysis

```{r message=FALSE, warning=FALSE}

model <- lm(data = combined2021, Total_EE_Investment ~ `Total population` + Female + child + `Median age (years)` + `Median household income (dollars)` + `Occupied housing units` + Gas + Electricity  + Disasters + `2021`, na.action = na.exclude)
summary(model)
#step(model)

model_2 <- lm(data = combined2021, Total_EE_Investment ~ `Total population` + child + `Median age (years)` + `Median household income (dollars)` + `Occupied housing units` + Gas + Electricity)
summary(model_2)
#step(model_2)

model_3 <- lm(data = combined2021, Total_EE_Investment~`Total population`+Electricity )
summary(model_3)


log_combined2021<- combined2021%>%
  mutate(log_pop=log(`Total population`),
         log_income=log(`Median household income (dollars)`),
         log_disaster=log(Disasters),
         log_EE_investment=log(Total_EE_Investment))

model_log <- lm(data = log_combined2021, log_EE_investment ~  log_disaster + `2021`, na.action = na.exclude)
summary(model_log)
#step(model)

plot2 <- ggplot(combined2021, aes(x=Disasters+`2021`, y = Total_EE_Investment))+
  geom_point()+
  geom_smooth(method = 'lm', )
plot2

plot <- ggplot(log_combined2021, aes(x=log_disaster+`2021`, y = log_EE_investment))+
  geom_point()+
  geom_smooth(method = 'lm', )
plot

 #the orginal data (disaster) does not follow normal distribution, thus need to be log-transformed for linear regression.

```


## Question 1: <insert specific question here and add additional subsections for additional questions below, if needed>

## Question 2: 




\newpage

# Summary and Conclusions


\newpage

# References
<add references here if relevant, otherwise delete this section> 
